# Generated by Django 4.0.3 on 2023-05-25 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('l_name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='uploads/employee/')),
                ('status', models.CharField(default='Not Selected', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='feed_back',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_emp', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=50, null=True)),
                ('l_name', models.CharField(blank=True, max_length=50, null=True)),
                ('DOB', models.DateField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=8, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='uploads/employee/')),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('empname', models.CharField(blank=True, max_length=50, null=True)),
                ('sheets', models.IntegerField(null=True)),
                ('pipe', models.IntegerField(blank=True, null=True)),
                ('other_meterial', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_cost', models.IntegerField(blank=True, default='0', null=True)),
                ('purchased_quantity', models.CharField(blank=True, max_length=50, null=True)),
                ('purchased_shop', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('name_of_employees', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_employees', models.IntegerField(blank=True, null=True)),
                ('workstart', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('total_days_to_complete', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='selectemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.employee')),
                ('name_of_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.user')),
            ],
        ),
    ]
